version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    docker:
      - image: cimg/base:stable
    parameters:
      node-version:
        type: string
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - node/install-packages:
          include-branch-in-cache-key: false
      - run:
          name: Node version
          command: node -v
      - run:
          name: Npm version
          command: npm -v
      - run:
          name: Validate TS types
          command: npm run typecheck
      - run:
          name: Validate prettier rules
          command: npm run prettier
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Unit tests and coverage
          command: npm run test:coverage:summary
workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version:
                - 14.19.1
                - 16.15.0
                - 18.0.0
